inputs = ['src\index.dlt', 'src\questao1.dlt', 'src\questao2.dlt', 'src\questao3.dlt', 'src\questao4.dlt', 'src\questao5.dlt']
out = "docs"

[document]
type = "book"
lang = "pt-BR"
theme-accent = "red"